#Select docker image
FROM node:14-buster-slim AS deps

#select directory
WORKDIR /app

#Add all dependencies
ADD package*.json ./ 

# install all dependencies 
RUN npm install
ADD . .

# run todoApp
CMD npm run dev